### ISSUE TITLE
1

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/interview-questions#2]
All the questions are number 1. Maybe this is deep and philosophical. Each question is as important as the last. Just because the questions are ordered doesn't mean that that order matters. If you can't answer a question, feel free to go on to the next---they are not all mandatory. 

Or maybe you just didn't expect indentation to render as code in markdown.

**Comment by tswicegood** [comment]
Fixed -- we can revert if that's what @tpn was really after. :-)
